// submission.test.ts — the tests frozen at Gate A for G6, asserting the README
// against the repository and the committed captures.
//
// Every numeric claim the README makes is checked here. Nothing in this file
// reaches the network or needs a key: the PR census is compared against
// docs/pr-census.json, a committed snapshot regenerated by
// `node scripts/pr-census.mjs`. Asserting against the live API instead would go
// red on every subsequent pull request and end up deleted.
//
// Two traps this file exists downstream of, both found by running an earlier
// draft rather than reading it:
//   - the audit captures key on `auditId`, not `id`;
//   - building a regex inside a template literal in this toolchain eats the
//     backslashes. Once the broken pattern still matched a row by accident,
//     which is green for the wrong reason. Table rows and goal labels are
//     therefore scanned, not matched, and each scan asserts it found something.

import { strict as assert } from "node:assert";
import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { describe, it } from "node:test";

const ROOT = new URL("..", import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1");
const README = readFileSync(join(ROOT, "README.md"), "utf8");
// The process record moved to its own file; the assertions moved with it rather
// than being relaxed. Helpers take the document so neither is read by accident.
const PROCESS = readFileSync(join(ROOT, "docs/PROCESS.md"), "utf8");
const cap = (f) => JSON.parse(readFileSync(join(ROOT, "docs/demo", f), "utf8"));
const norm = (s) => s.replace(/\s+/g, " ").trim();
const NL = String.fromCharCode(10);

/** Every two-column table row, as label -> raw right-hand cell. */
function textCells(doc = README) {
  const cells = new Map();
  for (const line of doc.split(NL)) {
    if (!line.trim().startsWith("|")) continue;
    const c = line.split("|").map((x) => x.trim());
    if (c.length >= 4 && c[1] && !c[1].startsWith("-")) {
      // Last-wins hid a duplicate label placed above the real row.
      assert.ok(!cells.has(c[1]), `duplicate table label: ${c[1]}`);
      cells.set(c[1], c[2]);
    }
  }
  assert.ok(cells.size > 0, "no table rows found — the scan is broken");
  return cells;
}

/**
 * The italic bullets under one heading. Scanning the whole README for `- *x*`
 * caught an unrelated bold bullet elsewhere in the file, so the marathon list is
 * read from its own section only.
 */
function bulletsUnder(heading, doc = PROCESS) {
  const at = doc.indexOf(heading);
  assert.ok(at !== -1, `no section: ${heading}`);
  const out = [];
  let inSection = false;
  let buffer = null;
  const flush = () => {
    if (buffer === null) return;
    // A bullet is closed by its trailing `*`. Reading line by line dropped the
    // one wrapped bullet and the `>= 5` floor was set to the broken count, so
    // the omission could not be detected by the assertion above it.
    assert.ok(buffer.endsWith("*"), `unterminated italic bullet: ${buffer.slice(0, 50)}`);
    out.push(norm(buffer.slice(1, -1)));
    buffer = null;
  };
  for (const line of doc.split(NL)) {
    if (line.startsWith(heading)) { inSection = true; continue; }
    if (!inSection) continue;
    if (line.startsWith("## ") || line.startsWith("### ")) break;
    const t = line.trim();
    if (t.startsWith("- *") && !t.startsWith("- **")) {
      flush();
      buffer = t.slice(2).trim();
      if (buffer.endsWith("*")) flush();
    } else if (buffer !== null) {
      if (!t) { flush(); continue; }
      buffer += " " + t;
      if (buffer.endsWith("*")) flush();
    }
  }
  flush();
  return out;
}

/** A cell like "5 — #10, #11, #32": its leading count and the PRs it names. */
function countAndPrs(cell) {
  const count = Number(cell.replace(/\*/g, "").trim().split(/[^0-9]/)[0]);
  const prs = [...cell.matchAll(/#([0-9]+)/g)].map((m) => Number(m[1])).sort((a, b) => a - b);
  return { count, prs };
}

/** The README's numeric table rows, as label -> number. */
function tableRows(doc = README) {
  const rows = new Map();
  for (const line of doc.split(NL)) {
    if (!line.trim().startsWith("|")) continue;
    const c = line.split("|").map((x) => x.trim());
    if (c.length >= 4 && /^[0-9]+$/.test(c[2])) {
      assert.ok(!rows.has(c[1]), `duplicate table label: ${c[1]}`);
      rows.set(c[1], Number(c[2]));
    }
  }
  assert.ok(rows.size > 0, "no numeric table rows found — the scan is broken");
  return rows;
}

describe("G6 — the submission README", () => {
  // AC1 — no scaffold text
  it("AC1 no scaffold text", () => {
    for (const s of ["create-mcp-use-app", "bootstrapped with", "## Getting Started",
                     "## Learn More", "localhost:3000/mcp/inspector"]) {
      assert.ok(!README.includes(s), `scaffold text present: ${s}`);
    }
  });

  // AC1 — every relative link resolves
  it("AC1 every relative link resolves", () => {
    const links = [...README.matchAll(/\]\((?!https?:)([^)#]+)\)/g)].map((m) => m[1]);
    assert.ok(links.length > 0, "no relative links found");
    for (const l of links) assert.ok(existsSync(join(ROOT, l)), `missing: ${l}`);
  });

  // AC2 — the self-audit figures come from the capture.
  //
  // Read as table cells. An earlier version built these with `new RegExp` inside
  // a template literal; the backslashes were eaten, the pattern compiled to
  // `|s*checkss*|s*32s*|`, whose empty alternatives match any string including
  // "", and the README's headline numbers were asserted by nothing. The file's
  // own header warned about exactly this and it happened anyway.
  it("AC2 self-audit figures match baseline-f4022c88.json", () => {
    const d = cap("baseline-f4022c88.json");
    const rows = tableRows();
    assert.equal(rows.get("checks"), d.checks.length);
    assert.equal(rows.get("passing"), d.checks.filter((c) => c.status === "pass").length);

    const cells = textCells();
    const failing = cells.get("failing");
    assert.ok(failing, "no `failing` row");
    const bad = d.checks.filter((c) => c.status !== "pass");
    assert.equal(Number(failing.split(",")[0].trim()), bad.length);
    assert.ok(failing.includes(bad[0].severity), `failing row must state severity ${bad[0].severity}`);

    for (const [label, flag] of [["`isReadyForChatgpt`", d.isReadyForChatgpt],
                                 ["`isReadyForClaudeai`", d.isReadyForClaudeai]]) {
      const cell = cells.get(label);
      assert.ok(cell, `no ${label} row`);
      assert.equal(cell.replace(/\*/g, "").trim(), String(flag),
        `${label}: README says ${cell}, capture says ${flag}`);
    }
  });

  // AC3 — the red check is named and the probe is cited
  it("AC3 red check named, probe cited", () => {
    const d = cap("baseline-f4022c88.json");
    const bad = d.checks.find((c) => c.status !== "pass");
    assert.ok(README.includes(bad.checkId), `README must name ${bad.checkId}`);
    assert.ok(README.includes(bad.severity), "severity not stated");
    assert.ok(README.includes("docs/demo/autofix-probe.md"), "probe not linked");
    assert.ok(README.includes("widgetMetadata"), "the unsatisfiable field not named");
  });

  // AC2 — the staged-failure captures
  it("AC2 staged-failure flags match the captures", () => {
    const red = cap("audit-red.json"), green = cap("audit-green.json");
    assert.equal(red.isReadyForChatgpt, false);
    assert.equal(red.isReadyForClaudeai, true, "the break moved one flag only");
    assert.equal(green.isReadyForChatgpt, true);
    assert.ok(README.includes(red.auditId.slice(0, 8)) && README.includes(green.auditId.slice(0, 8)));
  });

  // AC4 — the guard marathon entries exist in AGENTS.md, whitespace-collapsed
  it("AC4 marathon entries present in AGENTS.md", () => {
    const agents = norm(readFileSync(join(ROOT, "AGENTS.md"), "utf8"));
    const listed = bulletsUnder("### The guard marathon");
    assert.ok(listed.length >= 5, `expected the marathon list, found ${listed.length}`);
    for (const t of listed) assert.ok(agents.includes(t), `not in AGENTS.md: ${t.slice(0, 60)}`);
  });

  // AC4 — the gate bypasses and both BLOCK-overrides
  it("AC4 failure record is specific", () => {
    for (const pr of ["#10", "#11", "#21", "#28", "#32", "#8"]) {
      assert.ok(PROCESS.includes(pr), `bypass PR ${pr} not named`);
    }
    assert.ok(/merged over a live evaluator BLOCK/.test(PROCESS), "BLOCK-overrides not stated");
    assert.ok(!/zero BLOCKs/.test(PROCESS) || /zero BLOCK verdict objects/.test(PROCESS),
      "unqualified 'zero BLOCKs' — PR #11's body falsifies it");
    // The README must point at the record it no longer carries.
    assert.ok(README.includes("docs/PROCESS.md"), "README must link the process record");
  });

  // AC4 — the ledger figures in the README come from the ledger
  it("AC4 evaluation counts match docs/evaluations.md", () => {
    const led = readFileSync(join(ROOT, "docs/evaluations.md"), "utf8");
    let rounds = 0, blocks = 0, withFindings = 0;
    for (const line of led.split(NL)) {
      const c = line.split("|").map((x) => x.trim());
      // A round row is: | n | `sha` | VERDICT | what it found |
      if (c.length < 6 || !/^[0-9]+$/.test(c[1]) || !c[2].startsWith("`")) continue;
      rounds++;
      if (c[3] === "BLOCK") blocks++;
      if (c[4] && c[4] !== "—") withFindings++;
    }
    assert.ok(rounds > 0, "no ledger rows parsed — the scan is broken");
    const rows = tableRows(PROCESS);
    assert.equal(rows.get("evaluation rounds recorded"), rounds);
    assert.equal(rows.get("of which the evaluator returned BLOCK"), blocks);
    assert.equal(rows.get("rounds that produced at least one finding"), withFindings);
    // The plan requires the README to note PR #34's self-undercount rather than
    // quietly use the smaller number.
    assert.ok(PROCESS.includes("Nine rounds. Three BLOCKs."),
      "PR #34's undercount must be quoted, not summarised away");
    assert.ok(PROCESS.includes("All five were caught by an evaluator, not by me"),
      "AGENTS.md's coverage entry must be quoted");
  });

  // AC2 — the counts drawn from STAGE-PLAN.md and AGENTS.md
  it("AC2 correction and mistake-log counts match their files", () => {
    const rows = tableRows(PROCESS);
    const plan = readFileSync(join(ROOT, "docs/plans/STAGE-PLAN.md"), "utf8");
    // Corrections are numbered list items; the highest number is the count. A
    // naive count of numbered items gives 47, because the open-questions list at
    // the top restarts at 1.
    let highest = 0;
    for (const line of plan.split(NL)) {
      const m = line.match(/^([0-9]+)\. \*\*/);
      if (m) highest = Math.max(highest, Number(m[1]));
    }
    assert.ok(highest > 0, "no numbered corrections found — the scan is broken");
    assert.equal(rows.get("corrections in the stage plan"), highest);

    const agents = readFileSync(join(ROOT, "AGENTS.md"), "utf8");
    const log = agents.slice(agents.indexOf("## Mistake log"));
    const entries = log.split(NL).filter((l) => l.startsWith("- **")).length;
    assert.ok(entries > 0, "no mistake-log entries found — the scan is broken");
    assert.equal(rows.get("entries in the mistake log"), entries);
  });

  // AC4 — the marathon's span is the length of a checked list, not a claim
  it("AC4 the guard marathon span is verified entry by entry", () => {
    const agents = readFileSync(join(ROOT, "AGENTS.md"), "utf8");
    const log = agents.slice(agents.indexOf("## Mistake log"));
    const titles = [];
    let current = null;
    for (const line of log.split(NL)) {
      if (line.startsWith("- **")) {
        if (current !== null) titles.push(current);
        current = line.slice(4);
      } else if (current !== null && !current.includes("**")) {
        current += " " + line.trim();
      }
    }
    if (current !== null) titles.push(current);
    const clean = titles.map((t) => norm(t.split("**")[0]));
    assert.ok(clean.length > 50, `expected the full log, parsed ${clean.length}`);

    const cells = textCells(PROCESS);
    const span = cells.get("consecutive entries correcting one guard file");
    assert.ok(span, "no marathon row");
    const [from, to] = span.split("–").map((x) => Number(x.replace(/[^0-9]/g, "")));
    assert.ok(from > 0 && to > from, `unparseable span: ${span}`);
    assert.equal(tableRows(PROCESS).get("entries in that run"), to - from + 1);

    // Every entry the README lists must be inside the span — and the span's own
    // endpoints must be among them. Without the endpoints, any window of the
    // right length containing the samples passes: 34-51 and 35-52 both did.
    const inSpan = new Set(clean.slice(from - 1, to));
    const listed = bulletsUnder("### The guard marathon");
    assert.ok(listed.length > 0, "no marathon entries listed — the scan is broken");
    for (const t of listed) {
      assert.ok(inSpan.has(t), `README lists an entry outside ${from}-${to}: ${t.slice(0, 60)}`);
    }
    assert.ok(listed.includes(clean[from - 1]),
      `the span starts at ${from} but the README does not list that entry`);
    assert.ok(listed.includes(clean[to - 1]),
      `the span ends at ${to} but the README does not list that entry`);
  });

  // AC2 — the census cells that carry a count AND a PR list
  it("AC2 the red-merge and BLOCK-override cells match the fixture", () => {
    const c = JSON.parse(readFileSync(join(ROOT, "docs/pr-census.json"), "utf8"));
    const cells = textCells(PROCESS);
    for (const [label, expected] of [
      ["merged over a red required check", c.mergedOverRedGate],
      ["merged over a live evaluator BLOCK", c.mergedOverLiveBlock],
    ]) {
      const cell = cells.get(label);
      assert.ok(cell, `no "${label}" row`);
      const { count, prs } = countAndPrs(cell);
      assert.equal(count, expected.length, `${label}: cell says ${count}, fixture has ${expected.length}`);
      // Both directions. Filtering to the expected set let a cell name extra
      // PRs — claiming #34 was merged over a red gate would have passed.
      assert.deepEqual(prs, [...expected].sort((x, y) => x - y),
        `${label}: cell names ${prs}, fixture has ${expected}`);
    }
  });

  // AC2/AC4 — the author-found count is the length of the ledger's list
  it("AC4 the author-found count equals the ledger's list", () => {
    const led = readFileSync(join(ROOT, "docs/evaluations.md"), "utf8");
    const heading = "## Found by the author, not by an evaluation";
    const at = led.indexOf(heading);
    assert.ok(at !== -1, "the ledger must define the author-found list");
    const section = led.slice(at + heading.length);
    const end = section.indexOf(NL + "## ");
    const items = (end === -1 ? section : section.slice(0, end))
      .split(NL)
      .filter((l) => l.startsWith("- ")).length;
    assert.ok(items > 0, "no items parsed — the scan is broken");
    assert.equal(tableRows(PROCESS).get("defects the author noticed first"), items);
  });

  // AC3 — every autofix figure is read out of the probe record and required to
  // appear in the README. The previous version skipped any figure the README did
  // not already contain, so changing one made the check vanish rather than fail:
  // all six survived mutation, in the paragraph the README leans on hardest.
  it("AC3 autofix figures are the probe record's", () => {
    const probe = readFileSync(join(ROOT, "docs/demo/autofix-probe.md"), "utf8");
    const one = (re, what) => {
      const m = probe.match(re);
      assert.ok(m, `the probe record no longer states ${what} — this test is stale`);
      return m[1];
    };
    const elapsed = one(/Elapsed: \*\*([^*]+)\*\*/, "its elapsed time");
    const events = one(/([0-9]+) events/, "its event count");
    const bash = one(/`Bash` ([0-9]+)/, "its Bash count");
    const read = one(/`Read` ([0-9]+)/, "its Read count");
    const edits = one(/MultiEdit` calls\*\* \| \*\*([0-9]+)\*\*/, "its edit count");

    const para = README.slice(README.indexOf("The autofix probe"));
    assert.ok(para.includes(elapsed), `README must state the probe's elapsed time (${elapsed})`);
    assert.ok(para.includes(`${events} events`), `README must state ${events} events`);
    assert.ok(para.includes("`Bash` " + bash), `README must state Bash ${bash}`);
    assert.equal(read, "2", "the README words the Read count as 'twice'");
    assert.ok(/`Read`\s+twice/.test(para), "README must state Read twice");
    assert.equal(edits, "0", "the probe's edit count is the load-bearing zero");
    assert.ok(/\*\*zero\*\* `Edit`\/`Write` calls/.test(para), "README must state zero edits");
    assert.ok(/\*\*zero\*\* git mutations/.test(para), "README must state zero git mutations");
    assert.ok(probe.includes("200 OK") && para.includes("returned 200"),
      "the 200 response must come from the probe record");
    // The quoted conclusion is the whole point of the citation.
    const quote = "neither `widgetMetadata` nor `openai/widgetDescription` appears in the mcp-use";
    assert.ok(norm(probe).includes(norm(quote)), "the probe no longer carries the quote");
    assert.ok(norm(README).includes(norm(quote)), "the README must quote it verbatim");
  });

  // The ledger's Totals must agree with the rows it summarises. Round 2 found
  // the ledger contradicting itself in prose; this closes the numeric half.
  it("AC4 the ledger's totals agree with its own rows", () => {
    const led = readFileSync(join(ROOT, "docs/evaluations.md"), "utf8");
    const counts = { BLOCK: 0, "APPROVE-WITH-NOTES": 0, APPROVE: 0 };
    let rounds = 0;
    for (const line of led.split(NL)) {
      const c = line.split("|").map((x) => x.trim());
      if (c.length < 6 || !/^[0-9]+$/.test(c[1]) || !c[2].startsWith("`")) continue;
      rounds++;
      assert.ok(c[3] in counts, `unknown verdict in the ledger: ${c[3]}`);
      counts[c[3]]++;
    }
    assert.ok(rounds > 0, "no ledger rows parsed — the scan is broken");
    const totals = new Map();
    let inTotals = false;
    for (const line of led.split(NL)) {
      if (line.startsWith("## Totals")) { inTotals = true; continue; }
      if (inTotals && line.startsWith("## ")) break;
      if (!inTotals || !line.trim().startsWith("|")) continue;
      const c = line.split("|").map((x) => x.trim());
      if (c.length >= 4 && /^[0-9]+$/.test(c[2])) totals.set(c[1], Number(c[2]));
    }
    assert.ok(totals.size > 0, "no totals parsed — the scan is broken");
    assert.equal(totals.get("rounds"), rounds);
    for (const [verdict, n] of Object.entries(counts)) {
      assert.equal(totals.get(verdict), n, `Totals says ${totals.get(verdict)} ${verdict}, rows show ${n}`);
    }
  });

  // AC5 — the re-break decision
  it("AC5 re-break decision recorded", () => {
    assert.ok(/does \*\*not\*\* show|does not show/.test(README),
      "the README must state what the probe does not prove");
  });


  // AC2 — every census figure in the README equals the committed fixture
  it("AC2 census figures match docs/pr-census.json", () => {
    const c = JSON.parse(readFileSync(join(ROOT, "docs/pr-census.json"), "utf8"));
    const rows = tableRows(PROCESS);
    const want = {
      "pull requests opened": c.prsOpened,
      "merged": c.merged,
      "merged before the gate existed": c.mergedBeforeGateExisted.length,
      "passed the gate carrying a verdict": c.mergedGatePassedCarryingVerdict.length,
      "passed by the `[docs]` exemption, carrying none": c.mergedGatePassedByDocsExemption.length,
      "went red, then green once the verdict was added": c.redThenGreen.length,
    };
    for (const [label, n] of Object.entries(want)) {
      assert.ok(rows.has(label), `no census row labelled "${label}"`);
      assert.equal(rows.get(label), n, `${label}: README ${rows.get(label)} vs fixture ${n}`);
    }
    for (const n of c.mergedOverRedGate) assert.ok(PROCESS.includes("#" + n), `#${n} not named`);
    assert.equal(c.blockVerdictObjects.length, 1);
    assert.equal(c.blockVerdictObjects[0].state, "CLOSED");
  });

  // AC2/AC4 — the goal count comes from the stage plan, not from memory
  it("AC2 goal count matches STAGE-PLAN", () => {
    const plan = readFileSync(join(ROOT, "docs/plans/STAGE-PLAN.md"), "utf8");
    // Scanned, not matched by regex. Building a pattern in a template literal
    // silently eats the backslashes in this toolchain, and a broken pattern that
    // finds nothing looks exactly like a correct one finding nothing.
    const labels = new Set();
    const isWord = (ch) => ch !== undefined && /[0-9A-Za-z]/.test(ch);
    for (let i = 0; i < plan.length - 1; i++) {
      if (plan[i] !== "G") continue;
      const d = plan[i + 1];
      if (d < "1" || d > "9") continue;
      if (isWord(plan[i - 1]) || isWord(plan[i + 2])) continue;
      labels.add(d);
    }
    assert.ok(labels.size > 0, "found no goal labels — the scan is broken, not the plan");
    const rows = tableRows(PROCESS);
    assert.equal(rows.get("goals recorded in the stage plan"), labels.size,
      `README says ${rows.get("goals recorded in the stage plan")}, STAGE-PLAN names ${labels.size}`);
  });

});
